server:
  port: 6969

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/v1/**

        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/api/v1/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${DOMAIN}
          audience: ${DOMAIN}api/v2/