server:
  port: 6969

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}

spring:
  application:
    name: gateway
  config:
    import: optional:file:../.env[.properties]
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/v1/dish, /api/v1/dish/**, /api/v1/category, /api/v1/category/**
        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/api/v1/session, /api/v1/session/**, /api/v1/order, /api/v1/order/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurant, /api/v1/restaurant/**, /api/v1/ingredient, /api/v1/ingredient/**, /api/v1/table, /api/v1/table/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/register