server:
  port: 6969

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/api/v1/**
        - id: session-service
          uri: lb://SESSION-SERVICE
          predicates:
            - Path=/api/v1/**
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/v1/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${DOMAIN}
#          audience: ${AUDIENCE}