server:
  port: 6969

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
      non-secure-port: 80

spring:
  application:
    name: gateway
  config:
    import: optional:file:../.env[.properties]
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: ${MENU_URL:lb://menu-service}
          predicates:
            - Path=/api/v1/dish, /api/v1/dish/**, /api/v1/category, /api/v1/category/**
        - id: session-service
          uri: ${SESSION_URL:lb://session-service}
          predicates:
            - Path=/api/v1/session, /api/v1/session/**, /api/v1/order, /api/v1/order/**
        - id: restaurant-service
          uri: ${RESTAURANT_URL:lb://restaurant-service}
          predicates:
            - Path=/api/v1/restaurant, /api/v1/restaurant/**, /api/v1/ingredient, /api/v1/ingredient/**, /api/v1/table, /api/v1/table/**
        - id: notification-service
          uri: ${NOTIFICATION_URL:lb://notification-service}
          predicates:
            - Path=/register, /api/v1/notify/user-order-update, /api/v1/notify/waiter-table-update/**, /api/v1/notify/end-user-session/** 